jenkinsci/incrementals-tools

maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/ReincrementalifyMojo.java
To avoid breaking POM with `reincrementalify` if POM does not contain `revison` or `changelist` a change that https://github.com/jenkinsci/plugin-pom/pull/117 depends on
=> [JENKINS-51658] add NOOP to reincrementalify

enforcer-rules/pom.xml, enforcer-rules/src/main/java/io/jenkins/tools/incrementals/enforcer/RequireExtensionVersion.java, git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java, pom.xml
[JENKINS-51869](https://issues.jenkins-ci.org/browse/JENKINS-51869)
After release, needs a matching patch in `plugin-pom` to enforce it, something like
```xml
<rule implementation="io.jenkins.tools.incrementals.enforcer.RequireExtensionVersion">
<version>[1.0-beta-4,)</version>
</rule>
<dependencies>
<dependency>
<groupId>io.jenkins.tools.incrementals</groupId>
<artifactId>incrementals-enforcer-rules</artifactId>
<version>1.0-beta-4</version>
</dependency>
</dependencies>
```
and then updates to plugins already using the extension to start using the new version.
=> [JENKINS-51869] Drop --first-parent from rev count

maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/UpdateMojo.java
For example `mvn incrementals:update -Dbranch=jglick:logs-JENKINS-38381` on https://github.com/jenkinsci/workflow-support-plugin/pull/15 inappropriately tried to patch
```diff
diff --git a/pom.xml b/pom.xml
index 41e178b..b06364b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -68,10 +68,10 @@
<java.level>8</java.level>
<no-test-jar>false</no-test-jar>
<useBeta>true</useBeta>
-        <git-plugin.version>3.7.0</git-plugin.version>
+        <git-plugin.version>4.0.0-beta3</git-plugin.version>
<workflow-scm-step-plugin.version>2.6</workflow-scm-step-plugin.version>
-        <workflow-step-api-plugin.version>2.13</workflow-step-api-plugin.version>
-        <scm-api-plugin.version>2.2.6</scm-api-plugin.version>
+        <workflow-step-api-plugin.version>2.16</workflow-step-api-plugin.version>
+ …
```
=> updateProperties failed to honor the updateNonincremental flag

README.md
Assuming https://github.com/jenkins-infra/pipeline-library/pull/111 is merged.
=> Documenting usage of proposed new infra.prepareToPublishIncrementals

README.md, enforcer-rules/pom.xml, git-changelist-maven-extension/pom.xml, git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java, lib/pom.xml, maven-plugin/pom.xml, pom.xml
Enables alternate usages such as in https://github.com/jenkinsci/jep/pull/244#discussion_r294029302.
=> Make changelist.format configurable

README.md
Update to latest current version of git-changelist-maven-extension. Add a note to the reader to check for the latest version.
=> Update dependency version in documentation.

git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java, maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/IncrementalifyMojo.java
[JENKINS-58716](https://issues.jenkins-ci.org/browse/JENKINS-58716), matches https://github.com/jenkinsci/plugin-compat-tester/pull/181.
=> [JENKINS-58716] -DgitHubRepo when possible to infer

README.md
Noting https://github.com/jenkinsci/plugin-pom/pull/375 & https://github.com/jenkinsci/pom/pull/147.
=> [JEP-229] Noting stock block-MRP profile

README.md
Judging by https://github.com/jenkinsci/lib-version-number/pull/6/commits/00713139ac0106e77aca9f84c3b27e4848d00623 this should work better to support [backport branches](https://gist.github.com/jglick/86a30894446ed38f918050c1180483e2).
=> Prefer -Dchangelist.format=%d.v%s

git-changelist-maven-extension/pom.xml, git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java, git-changelist-maven-extension/src/test/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/MainTest.java
Fixes https://github.com/jenkins-infra/jenkins.io/issues/4783 by converting (e.g.) `852b473a2b8c` which parses as `852-beta-473-alpha-2-beta-8-c` to `852b_473a_2b_8c` which parses as `852-b_-473-a_-2-b_-8-c`. A bit ugly but I did not see a better approach. Tried just capitalizing the hash, but this does not work—the comparisons are apparently case-insensitive.
Could probably be more conservative and only replace `[ab]` when these are not surrounded by other letters (`[a-f]`); not sure if anyone cares.
As in https://github.com/jenkins-infra/incrementals-publisher/pull/14, at least https://github.com/jenkins-infra/incrementals-publisher/blob/00be8881121de3bb26ba91605aafedeecbba7435/lib/pipeline.js#L70 would likely need to be amended as well for JEP-305 deployments (should be irrelevant for …
=> Prevent `[ab][0-9]` in commit hashes from being treated as `alpha` or `beta`

README.md
This is due to Maven 4 support [1].
Building plugins with Maven 4 (alpha) fails with:
> 'profiles.profile[consume-incrementals].repositories.repository.[incrementals].url' contains an expression but should be a constant. @ org.jenkins-ci.plugins:plugin:4.53
This has already been reported to Jenkins [2] and Maven [3] and was declared as an intentional change.
[1] https://github.com/jenkinsci/plugin-pom/pull/666 
[2] https://issues.jenkins.io/browse/JENKINS-67878 
[3] https://issues.apache.org/jira/browse/MNG-7420
=> Fixes offline instructions due to removal of incrementals.url property

git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java, git-changelist-maven-extension/src/test/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/MainTest.java
Closes #34 by reverting the logic change in #31.
=> Restore trailing slash after `a` or `b`

enforcer-rules/pom.xml, enforcer-rules/src/main/java/io/jenkins/tools/incrementals/enforcer/RequireExtensionVersion.java, git-changelist-maven-extension/pom.xml, lib/pom.xml, lib/src/main/java/io/jenkins/tools/incrementals/lib/UpdateChecker.java, maven-plugin/pom.xml, maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/IncrementalifyMojo.java, maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/UpdateMojo.java, maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/util/PluginRef.java, maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/util/PluginRefList.java, pom.xml
See https://github.com/jenkinsci/pom/pull/387 and https://github.com/jenkinsci/plugin-pom/pull/689. We cannot update Maven Enforcer Plugin to the latest version until this component is recompiled against recent Maven APIs.
I tested each component manually (with Enforcer 3.2.1):
- `RequireExtensionVersion` with valid version
- `RequireExtensionVersion` with invalid version
- Unincrementalified a plugin, stepped through the modified code in `IncrementalifyMojo` in a debugger, verified the changes to `pom.xml` were as expected
- Stepped through the modified code in `UpdateMojo` in a debugger, verified the mojo completed without any errors
- Jenkins core build with these changes
- Text Finder plugin build with these changes
CC @jglick
=> Refresh component for January 2023

.github/dependabot.yml, maven-plugin/pom.xml, pom.xml
use a version of maven libs that we expect to be satisfied by consumers.
cf https://github.com/jenkinsci/maven-hpi-plugin/pull/440#issuecomment-1454825697
=> set maven libs according to consumers

.github/workflows/maven.yml
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
=> Run CI on `ubuntu-latest`

enforcer-rules/src/main/java/io/jenkins/tools/incrementals/enforcer/RequireExtensionVersion.java, lib/src/main/java/io/jenkins/tools/incrementals/lib/UpdateChecker.java
Javadoc generation failed on Java 20 for me, because javadoc got stricter since Java 8. The change proposed addresses the warnings and errors.
=> Fix javadoc errors on java 20

.github/dependabot.yml, .github/workflows/maven.yml, git-changelist-maven-extension/pom.xml, pom.xml
Like https://github.com/jenkinsci/incrementals-tools/pull/49, but pinning v5 because v6 requires Java 11 or newer and this tool's GH action is bound to Java 8.
Closes https://github.com/jenkinsci/incrementals-tools/pull/49
Closes https://github.com/jenkinsci/incrementals-tools/pull/39
=> Bump org.eclipse.jgit from 4.9.0.201710071750-r to 6.5.0.202303070854-r

git-changelist-maven-extension/pom.xml, git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java
References:
- https://cwiki.apache.org/confluence/display/MAVEN/Maven+Ecosystem+Cleanup
- https://maven.apache.org/maven-jsr330.html
- https://github.com/eclipse/sisu.plexus/wiki/Plexus-to-JSR330
Ran a build of Text Finder with `-Dset.changelist` and these changes.
Fixes #62
=> Migrate from deprecated Plexus Components to non-deprecated JSR 330

maven-plugin/pom.xml
#64 seems to break tests _locally_ for some reason. (But not on CI, which is still using Maven 3.8.8.)
```console
$ mvn -pl maven-plugin surefire:test
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------< io.jenkins.tools.incrementals:incrementals-maven-plugin >-------
[INFO] Building incrementals-maven-plugin 1.7-SNAPSHOT
[INFO]   from pom.xml
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO] 
[INFO] --- surefire:3.1.2:test (default-cli) @ incrementals-maven-plugin ---
[INFO] Using auto detected provider …
```
=> Revert "Merge pull request #64 from jenkinsci/dependabot/maven/org.codehaus.mojo-versions-maven-plugin-2.16.0"

git-changelist-maven-extension/pom.xml, maven-plugin/pom.xml
Looks like something went wrong when I updated my fork.
https://github.com/jenkinsci/incrementals-tools/pull/72/files#diff-5b09e4f9360590e6d4eab0d4b50393fb060ce2dcf7d889f154a99a1830c3c7bbR81 is not supposed to be here.
The change proposed reverts the bad merge.
=> Fixup bad merge in #72

git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java
Add support for Maven reproducible builds when Maven Release Plugin is not in use, regardless of whether `project.build.outputTimestamp` is (as would be the case for a plugin that still used MRP for production releases but used Incrementals for PR releases) or is not (as would be the case for a plugin that fully implemented automated release) defined in `pom.xml`.
Verified that when passing `-Dset.changelist` Maven couldn't verify an incrementals build with `mvn clean verify artifact:compare` before this PR but could verify it after this PR.
Fixes #103
=> Support for Maven reproducible builds

enforcer-rules/pom.xml, lib/pom.xml, maven-plugin/pom.xml
When attempting to publish the last release to Maven Central:
```
[INFO] Deployment failed
[INFO] pkg:maven/io.jenkins.tools.incrementals/lib@1.9:
[INFO]  - Project name is missing
[INFO]
[INFO] pkg:maven/io.jenkins.tools.incrementals/incrementals-enforcer-rules@1.9:
[INFO]  - Project name is missing
[INFO]
[INFO] pkg:maven/io.jenkins.tools.incrementals/incrementals-maven-plugin@1.9:
[INFO]  - Project name is missing
```
=> Add missing names
